language: node_js
sudo: false
node_js:
    - 8
    - 10
    - 12
    - 13
notifications:
    email:
        recipients:
            - andris@kreata.ee
        on_success: change
        on_failure: change
